# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4

branches:
  only:
    - master
    - develop

before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: bin/phpspec run -v
notifications:
  irc:
    channels:
     - "irc.freenode.org#yamaki-project"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
